spring:
  application:
    name: cardopen
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/card?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: leadeon
    password: leadeon
server:
  servlet:
    context-path: /cardopen
  port: 8001
mybatis:
  mapper-locations: classpath:/mybatis/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
file:
  path: E:/工作空间/cardopen/out/production/resources/static/
  readPath: http://192.168.0.106:8001/cardopen/